(defvar jaseem/packages '(
                          ac-slime
                          apache-mode
                          auctex
                          auto-compile
                          auto-complete
                          auto-indent-mode
                          autopair
                          bash-completion
                          bitlbee
                          buster-mode
                          buster-snippets
                          centered-cursor-mode
                          cl-lib
                          clojure-mode
                          cm-mode
                          cmake-mode
                          cmake-project
                          coffee-mode
                          combinators
                          creole
                          crontab-mode
                          csv-mode
                          dash
                          desktop
                          dired+
                          doc-mode
                          dropdown-list
                          eimp
                          elixir-mode
                          elixir-yasnippets
                          emmet-mode
                          erlang
                          findr
                          flymake
                          flymake-easy
                          flymake-haskell-multi
                          flymake-hlint
                          gh
                          gist
                          git-commit-mode
                          gitconfig-mode
                          gitignore-mode
                          guru-mode
                          hackernews
                          haml-mode
                          handlebars-mode
                          haskell-mode
                          httpcode
                          inflections
                          jade-mode
                          js2-mode
                          js2-refactor
                          json-mode
                          jump
                          kv
                          less-css-mode
                          logito
                          lorem-ipsum
                          lua-mode
                          magit
                          markdown-mode
                          marmalade
                          nginx-mode
                          org
                          packed
                          paredit
                          pcache
                          rainbow-mode
                          slime
                          smex
                          solarized-theme
                          sws-mode
                          web-beautify
                          web-mode
                          yaml-mode
                          yasnippet
                          zencoding-mode)
  "Default packages")
